project:
  type: website

website:
  title: "spark_map"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: how-to-build.qmd
        text: How to build
      - text: Function Reference
        menu:
          - text: In english
            href: reference-en.qmd
          - text: Em português
            href: reference-ptbr.qmd
      - text: Articles
        menu:
          - text: In english
            href: articles-en.qmd
          - text: Em português
            href: articles-ptbr.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



