project:
  type: website

website:
  title: "spark_map"
  navbar:
    left:
      - href: https://github.com/pedropark99/spark_map/issues
        text: Report an issue
      - href: how-to-build.qmd
        text: How to build
      - href: how-to-test.qmd
        text: How to test
      - text: Function Reference
        menu:
          - text: In english
            href: reference-en.qmd
          - text: Em português
            href: reference-ptbr.qmd
      - text: Articles
        menu:
          - text: In english
            href: articles-en.qmd
          - text: Em português
            href: articles-ptbr.qmd
    right: 
      - icon: github
        href: https://github.com/pedropark99/spark_map

format:
  html:
    theme: solar
    css: styles.css
    toc: true



